version: '3.9'
services:
  mongo:
    image: mongo
  rainfall:
    build: .
    ports:
      - '8080:80'
    volumes:
      - ./app:/app/
      - /var/data/rainfall:/var/data/
    links:
      - mongo
    restart: always
    depends_on:
      - mongo